# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6637805c66e505b1dc5777281d065a3a41aaf181848e764d1728d78209c0cee7f6da93489bdd07253a7955af622263c737e7a2558a6415d3e9725cc1e58427fd

test:
  secret_key_base: c15e0074478a6b5c4dc230dfca446312ad6a2c0f85f4924f63cf8c7eef5e02035db9dece781b406146bd4deda08504b76660d9fd18e30ec19ac8808538324d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
